-- ============================================================
-- EKSJK V2 本地开发环境 — 数据库 Schema
-- 说明：基于 V2 Entity 类生成，使用 MyBatis-Plus 驼峰转下划线映射
-- 数据库：eksjk_local
-- ============================================================

-- 用户表（兼容 V1 Django AbstractUser 结构）
CREATE TABLE IF NOT EXISTS login_user (
    id                  BIGINT AUTO_INCREMENT PRIMARY KEY,
    password            VARCHAR(255),
    last_login          DATETIME,
    is_superuser        TINYINT(1) DEFAULT 0,
    username            VARCHAR(150) NOT NULL UNIQUE,
    first_name          VARCHAR(150) DEFAULT '',
    last_name           VARCHAR(150) DEFAULT '',
    email               VARCHAR(254) DEFAULT '',
    is_staff            TINYINT(1) DEFAULT 0,
    is_active           TINYINT(1) DEFAULT 1,
    date_joined         DATETIME DEFAULT CURRENT_TIMESTAMP,
    name                VARCHAR(100),
    sex                 VARCHAR(10),
    unit                VARCHAR(50),
    level               INT DEFAULT 0,
    professional        VARCHAR(50),
    date_update         DATETIME,
    department          VARCHAR(100),
    role_code           VARCHAR(50),
    password_changed_at DATETIME,
    wx_openid           VARCHAR(100),
    phone               VARCHAR(20),
    job_number          VARCHAR(50),
    is_deleted          INT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 医疗机构/单位表
CREATE TABLE IF NOT EXISTS login_unit (
    id              BIGINT AUTO_INCREMENT PRIMARY KEY,
    unit_name       VARCHAR(200),
    del_flg         VARCHAR(2) DEFAULT '1',
    unit_short_name VARCHAR(100),
    unit_code       VARCHAR(50),
    contact_name    VARCHAR(100),
    contact_phone   VARCHAR(20),
    contact_address VARCHAR(500),
    zip_code        VARCHAR(10),
    unit_level      VARCHAR(50),
    unit_type       VARCHAR(50),
    province        VARCHAR(50),
    city            VARCHAR(50),
    district        VARCHAR(50),
    status          INT DEFAULT 1,
    remark          VARCHAR(500),
    created_at      DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME,
    creator_id      BIGINT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 患者主表
CREATE TABLE IF NOT EXISTS datamain_patient (
    id                  BIGINT AUTO_INCREMENT PRIMARY KEY,
    dis_class           VARCHAR(20),
    case_num            VARCHAR(50),
    medrec_num          VARCHAR(50),
    user_num            VARCHAR(50),
    name                VARCHAR(100),
    sex                 VARCHAR(10),
    birth_time          DATETIME,
    relation            VARCHAR(50),
    self_tel            VARCHAR(20),
    doctor_name         VARCHAR(100),
    gonadal_sex         VARCHAR(10),
    AGEy                VARCHAR(10),
    AGEm                VARCHAR(10),
    chi_com             TEXT,
    age                 VARCHAR(20),
    ethnic              VARCHAR(50),
    height              VARCHAR(20),
    weight              VARCHAR(20),
    bmi                 VARCHAR(20),
    rbone_age           VARCHAR(20),
    cbone_age           VARCHAR(20),
    FHt                 VARCHAR(20),
    MHt                 VARCHAR(20),
    FHw                 VARCHAR(20),
    MHw                 VARCHAR(20),
    men_age             VARCHAR(20),
    is_bot              VARCHAR(10),
    family_his          TEXT,
    ges_week            VARCHAR(10),
    BWt                 VARCHAR(20),
    BL                  VARCHAR(20),
    cesa_sec            VARCHAR(50),
    fet_pro_his         TEXT,
    past_his            TEXT,
    cesa_asphyxia       VARCHAR(50),
    parity              VARCHAR(10),
    pronum              VARCHAR(10),
    pregnancy_infection TEXT,
    fir_vis_time        DATETIME,
    fir_vis_age         VARCHAR(20),
    ICD                 VARCHAR(50),
    is_finalhei         VARCHAR(10),
    xcx_card            VARCHAR(100),
    expected_height     VARCHAR(20),
    current_city        VARCHAR(100),
    past_time           DATETIME,
    past_height         VARCHAR(20),
    past_weight         VARCHAR(20),
    baby_flag           VARCHAR(10),
    myself_picture      VARCHAR(500),
    contacts_name       VARCHAR(100),
    contacts_num        VARCHAR(20),
    p_emial             VARCHAR(100),
    idcard              VARCHAR(50),
    nat_pla             VARCHAR(100),
    fam_adr             VARCHAR(500),
    card                VARCHAR(50),
    imp_per             VARCHAR(100),
    up_mec              VARCHAR(200),
    hospital_name       VARCHAR(200),
    c_time              DATETIME DEFAULT CURRENT_TIMESTAMP,
    modify_time         DATETIME,
    modify_per          VARCHAR(100),
    del_flg             VARCHAR(2) DEFAULT '1',
    tags                VARCHAR(500),
    confuse_name        VARCHAR(100),
    upper_case          VARCHAR(100),
    photo               VARCHAR(500),
    address             VARCHAR(500),
    category_describe   TEXT,
    enrollment_num      VARCHAR(50),
    enrollment_time     DATETIME,
    one_time            DATETIME,
    eltm_id             VARCHAR(50),
    sync_status         VARCHAR(20),
    sync_time           DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 随访记录表
CREATE TABLE IF NOT EXISTS datamain_patfoll (
    id                  BIGINT AUTO_INCREMENT PRIMARY KEY,
    patient_id          BIGINT,
    foll_time           DATETIME,
    up_time             DATETIME,
    age                 VARCHAR(20),
    Ht                  VARCHAR(20),
    Wt                  VARCHAR(20),
    bmi                 VARCHAR(20),
    body_fat            VARCHAR(20),
    waistline           VARCHAR(20),
    hips                VARCHAR(20),
    waist_to_hip_ratio  VARCHAR(20),
    rbone_age           VARCHAR(20),
    cbone_age           VARCHAR(20),
    gen_stag            VARCHAR(50),
    pub_stag            VARCHAR(50),
    IGF1                VARCHAR(20),
    IGFBP3              VARCHAR(20),
    Jiagong             TEXT,
    fas_blood_glu       VARCHAR(20),
    fas_insulin         VARCHAR(20),
    gly_hem             VARCHAR(20),
    liv_kid_lip         TEXT,
    LH                  VARCHAR(20),
    FSH                 VARCHAR(20),
    E2                  VARCHAR(20),
    T                   VARCHAR(20),
    DHT                 VARCHAR(20),
    yltg                VARCHAR(20),
    SHBG                VARCHAR(20),
    gon_b_ult           TEXT,
    tes_size            VARCHAR(50),
    bon_min_den         VARCHAR(50),
    dia_trea_plan       TEXT,
    other_medicine      TEXT,
    beh_dev_ass         VARCHAR(50),
    ped_mot_dev_ass     TEXT,
    gro_mot             VARCHAR(50),
    ind_soc             VARCHAR(50),
    lis_lan             VARCHAR(50),
    han_eye_coo         VARCHAR(50),
    vis_rep             VARCHAR(50),
    pra_rea             VARCHAR(50),
    wec_sca             VARCHAR(50),
    is_finalhei         VARCHAR(10),
    other               TEXT,
    image               TEXT,
    lab_exa_other       TEXT,
    lab_exa_mas         TEXT,
    disease             VARCHAR(200),
    dsdk                VARCHAR(200),
    clls                VARCHAR(200),
    qtyl                VARCHAR(200),
    other_exam          TEXT,
    eos                 VARCHAR(200),
    other_ima_name      VARCHAR(500),
    del_flg             VARCHAR(2) DEFAULT '1'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- MAS 随访记录表
CREATE TABLE IF NOT EXISTS datamain_masfoll (
    id             BIGINT AUTO_INCREMENT PRIMARY KEY,
    mas_id         BIGINT,
    is_finalhei    VARCHAR(10),
    is_per_pre     VARCHAR(10),
    per_pre_sf     TEXT,
    is_hyper       VARCHAR(10),
    hyper_sf       TEXT,
    hyper_jc       TEXT,
    is_gro_hor     VARCHAR(10),
    gro_hor_sf     TEXT,
    gro_hor_jc     TEXT,
    is_tre_hpy     VARCHAR(10),
    tre_hpy_sf     TEXT,
    tre_hpy_jc     TEXT,
    is_inc_cor     VARCHAR(10),
    inc_cor_sf     TEXT,
    inc_cor_jc     TEXT,
    is_int_sur     VARCHAR(10),
    is_bil_adr     VARCHAR(10),
    is_bon_pai     VARCHAR(10),
    bon_pai_sf     TEXT,
    bon_pai_jc     TEXT,
    hypop          VARCHAR(10),
    hypop_sf       TEXT,
    hypop_jc       TEXT,
    is_ske_sur     VARCHAR(10),
    is_cafe_spot   VARCHAR(10),
    is_psy_cou     VARCHAR(10),
    sur_sta        VARCHAR(50),
    del_flg        VARCHAR(2) DEFAULT '1'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 疾病病例子表：DSD（性发育异常）
CREATE TABLE IF NOT EXISTS datamain_case (
    id                  BIGINT AUTO_INCREMENT PRIMARY KEY,
    patient_id          BIGINT,
    karyotype           VARCHAR(100),
    gonadal_status      VARCHAR(200),
    external_genitalia  TEXT,
    internal_genitalia  TEXT,
    hormone_levels      TEXT,
    diagnosis           TEXT,
    treatment_plan      TEXT,
    create_time         DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time         DATETIME,
    is_deleted          INT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 疾病病例子表：FSS（遗传性骨病）
CREATE TABLE IF NOT EXISTS datamain_short (
    id              BIGINT AUTO_INCREMENT PRIMARY KEY,
    patient_id      BIGINT,
    bone_age        VARCHAR(20),
    height_sds      VARCHAR(20),
    genetic_test    TEXT,
    diagnosis       TEXT,
    treatment_plan  TEXT,
    create_time     DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time     DATETIME,
    is_deleted      INT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 疾病病例子表：CPP（中枢性性早熟）
CREATE TABLE IF NOT EXISTS datamain_sexprecocity (
    id                BIGINT AUTO_INCREMENT PRIMARY KEY,
    patient_id        BIGINT,
    onset_age         VARCHAR(20),
    bone_age_advance  VARCHAR(20),
    lh_peak           VARCHAR(20),
    fsh_peak          VARCHAR(20),
    diagnosis         TEXT,
    treatment_plan    TEXT,
    create_time       DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time       DATETIME,
    is_deleted        INT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 疾病病例子表：MAS（McCune-Albright 综合征）
CREATE TABLE IF NOT EXISTS datamain_mas (
    id                  BIGINT AUTO_INCREMENT PRIMARY KEY,
    patient_id          BIGINT,
    cafe_au_lait_spots  VARCHAR(200),
    fibrous_dysplasia   VARCHAR(200),
    precocious_puberty  VARCHAR(200),
    thyroid_abnormality VARCHAR(200),
    gh_excess           VARCHAR(200),
    cushing_syndrome    VARCHAR(200),
    phosphate_wasting   VARCHAR(200),
    diagnosis           TEXT,
    treatment_plan      TEXT,
    create_time         DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time         DATETIME,
    is_deleted          INT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 疾病病例子表：SGA（小于胎龄儿）
CREATE TABLE IF NOT EXISTS datamain_sga (
    id               BIGINT AUTO_INCREMENT PRIMARY KEY,
    patient_id       BIGINT,
    birth_weight     VARCHAR(20),
    birth_length     VARCHAR(20),
    gestational_age  VARCHAR(20),
    catch_up_growth  VARCHAR(50),
    diagnosis        TEXT,
    treatment_plan   TEXT,
    create_time      DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time      DATETIME,
    is_deleted       INT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 疾病病例子表：SSS（Silver-Russell 综合征 / 家族性矮小）
CREATE TABLE IF NOT EXISTS datamain_jzxshort (
    id              BIGINT AUTO_INCREMENT PRIMARY KEY,
    patient_id      BIGINT,
    father_height   VARCHAR(20),
    mother_height   VARCHAR(20),
    target_height   VARCHAR(20),
    genetic_test    TEXT,
    diagnosis       TEXT,
    treatment_plan  TEXT,
    create_time     DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time     DATETIME,
    is_deleted      INT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 疾病病例子表：ELTM（E路童萌）
CREATE TABLE IF NOT EXISTS datamain_szfyeltm (
    id               BIGINT AUTO_INCREMENT PRIMARY KEY,
    patient_id       BIGINT,
    screening_result VARCHAR(200),
    assessment_data  TEXT,
    diagnosis        TEXT,
    treatment_plan   TEXT,
    create_time      DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time      DATETIME,
    is_deleted       INT DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 学校健康筛查 — 学生表
CREATE TABLE IF NOT EXISTS school_student (
    id           BIGINT AUTO_INCREMENT PRIMARY KEY,
    doctor       VARCHAR(100),
    phone        VARCHAR(20),
    hhzgx        VARCHAR(50),
    num          VARCHAR(50),
    sclass       VARCHAR(50),
    name         VARCHAR(100),
    sex          VARCHAR(10),
    birth_time   DATETIME,
    height       VARCHAR(20),
    weight       VARCHAR(20),
    mqjycd       VARCHAR(50),
    fqjycd       VARCHAR(50),
    jtnsr        VARCHAR(50),
    zyjhr        VARCHAR(100),
    zhrjycd      VARCHAR(50),
    isxdjm       VARCHAR(10),
    yszdrstlb    VARCHAR(200),
    yszdrsgxy    VARCHAR(200),
    yldisbz      VARCHAR(200),
    yszdyybl     VARCHAR(200),
    fmfs         VARCHAR(50),
    bweight      VARCHAR(20),
    bweek        VARCHAR(10),
    csiszxqj     VARCHAR(50),
    cswyfs       VARCHAR(50),
    dmrsj        DATETIME,
    jfssj        DATETIME,
    imp_per      VARCHAR(100),
    up_mec       VARCHAR(200),
    c_time       DATETIME DEFAULT CURRENT_TIMESTAMP,
    modify_time  DATETIME,
    del_flg      VARCHAR(2) DEFAULT '1',
    count        VARCHAR(20)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 小程序图表用户表
CREATE TABLE IF NOT EXISTS xcx_chartuser (
    id               BIGINT AUTO_INCREMENT PRIMARY KEY,
    openid           VARCHAR(100),
    `key`            VARCHAR(100),
    medrec_num       VARCHAR(50),
    phone_num        VARCHAR(20),
    doctor           VARCHAR(100),
    is_tongb         VARCHAR(10),
    del_flg          VARCHAR(2) DEFAULT '1',
    new_user_flag    VARCHAR(10),
    myself_picture   VARCHAR(500),
    contacts_name    VARCHAR(100),
    contacts_num     VARCHAR(20),
    p_emial          VARCHAR(100),
    idcard           VARCHAR(50),
    nat_pla          VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
