-- ============================================================
-- EKSJK V2 本地开发环境 — 学校筛查模块表
-- 说明：问卷/活动/屏幕暴露/身体活动等子表，通过 student_id 关联 school_student
-- ============================================================

-- CBQ 儿童行为问卷
CREATE TABLE IF NOT EXISTS school_cbq (
    id           BIGINT AUTO_INCREMENT PRIMARY KEY,
    student_id   BIGINT,
    zscm         TEXT,
    bzzsl        TEXT,
    htzz         TEXT,
    xhmxhd       TEXT,
    xcsba        TEXT,
    nwczb        TEXT,
    mrjrxdf      TEXT,
    jtjhmdx      TEXT,
    xhdtrcg      TEXT,
    drhrbjs      TEXT,
    hpyz         TEXT,
    nzyfmxyf     TEXT,
    gxhaj        TEXT,
    sqgcsj       TEXT,
    trjccsj      TEXT,
    dqqgk        TEXT,
    bwcjs        TEXT,
    syayqxd      TEXT,
    hcsjsyxhj    TEXT,
    gmssby       TEXT,
    xhgq         TEXT,
    hhx          TEXT,
    ryaf         TEXT,
    zyktxsw      TEXT,
    wsjlcp       TEXT,
    bhphy        TEXT,
    zztscsj      TEXT,
    bxhcyyx      TEXT,
    qwcsbxf      TEXT,
    zywx         TEXT,
    hmzs         TEXT,
    bnzdhsc      TEXT,
    xhrhhd       TEXT,
    xrshx        TEXT,
    pyzhfz       TEXT,
    dfmwbpj      TEXT,
    c_time       DATETIME DEFAULT CURRENT_TIMESTAMP,
    modify_time  DATETIME,
    del_flg      VARCHAR(2) DEFAULT '1',
    count        VARCHAR(20)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- CCHKN 量表
CREATE TABLE IF NOT EXISTS school_cchkn (
    id           BIGINT AUTO_INCREMENT PRIMARY KEY,
    student_id   BIGINT,
    ntlbrgs      TEXT,
    bad          TEXT,
    jcdzt        TEXT,
    lyfx         TEXT,
    jcfpq        TEXT,
    bjgd         TEXT,
    bjsc         TEXT,
    hdyy         TEXT,
    lybz         TEXT,
    jczlba       TEXT,
    yhpy         TEXT,
    cjqfbr       TEXT,
    jcbgx        TEXT,
    sxpyxh       TEXT,
    ryfx         TEXT,
    xhjjz        TEXT,
    dljxyh       TEXT,
    jcshqp       TEXT,
    sbrzn        TEXT,
    zybzbr       TEXT,
    zsqxqc       TEXT,
    htdx         TEXT,
    hdrrq        TEXT,
    ryjx         TEXT,
    zylcj        TEXT,
    c_time       DATETIME DEFAULT CURRENT_TIMESTAMP,
    modify_time  DATETIME,
    del_flg      VARCHAR(2) DEFAULT '1',
    count        VARCHAR(20)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 母亲照养方式问卷
CREATE TABLE IF NOT EXISTS school_mqzyfs (
    id           BIGINT AUTO_INCREMENT PRIMARY KEY,
    student_id   BIGINT,
    hzbgxbpp     TEXT,
    hzysmgsm     TEXT,
    hzsffcwsw    TEXT,
    hzgxbxyq     TEXT,
    hzbfcdm      TEXT,
    hzfcbzh      TEXT,
    hzyddycgfzj  TEXT,
    glhzzs       TEXT,
    thzzs        TEXT,
    gjhzxqpytc   TEXT,
    dhzknysdc    TEXT,
    yxchtw       TEXT,
    bxbgjz       TEXT,
    wmyyzpp      TEXT,
    bnfwzwn      TEXT,
    bxhzzcn      TEXT,
    rhzmbwsm     TEXT,
    dhzshysgx    TEXT,
    bzyhzzsm     TEXT,
    zjmblchz     TEXT,
    hzxzmyjzy    TEXT,
    bqsjbyhz     TEXT,
    bljhzhfuzsm  TEXT,
    ysdfsbyhz    TEXT,
    wlyqysmz     TEXT,
    dhzmyjc      TEXT,
    bhzjjkn      TEXT,
    khzzs        TEXT,
    dhzrzhd      TEXT,
    tyjsysyx     TEXT,
    dhzbjsf      TEXT,
    hsyqyty      TEXT,
    thzyqyx      TEXT,
    yqhzjyy      TEXT,
    hzzcyspp     TEXT,
    bgxxs        TEXT,
    slshzsc      TEXT,
    ysqz         TEXT,
    zjmjtyq      TEXT,
    pyhzjzjd     TEXT,
    c_time       DATETIME DEFAULT CURRENT_TIMESTAMP,
    modify_time  DATETIME,
    del_flg      VARCHAR(2) DEFAULT '1',
    count        VARCHAR(20)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 屏幕暴露量表
CREATE TABLE IF NOT EXISTS school_pmbl (
    id           BIGINT AUTO_INCREMENT PRIMARY KEY,
    student_id   BIGINT,
    dycyn        TEXT,
    mtjcsj       TEXT,
    jztx         TEXT,
    ptgksj       TEXT,
    ptgkjlsj     TEXT,
    c_time       DATETIME DEFAULT CURRENT_TIMESTAMP,
    modify_time  DATETIME,
    del_flg      VARCHAR(2) DEFAULT '1',
    count        VARCHAR(20)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 亲子活动量表
CREATE TABLE IF NOT EXISTS school_qzhd (
    id           BIGINT AUTO_INCREMENT PRIMARY KEY,
    student_id   BIGINT,
    yhzyqks      TEXT,
    jhzsdgl      TEXT,
    tthh         TEXT,
    yhzyqyx      TEXT,
    yqsz         TEXT,
    yqcg         TEXT,
    jgs          TEXT,
    zsg          TEXT,
    zyd          TEXT,
    jhzzl        TEXT,
    yhztlzw      TEXT,
    yhzrsdzr     TEXT,
    c_time       DATETIME DEFAULT CURRENT_TIMESTAMP,
    modify_time  DATETIME,
    del_flg      VARCHAR(2) DEFAULT '1',
    count        VARCHAR(20)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 睡眠习惯量表
CREATE TABLE IF NOT EXISTS school_smxg (
    id           BIGINT AUTO_INCREMENT PRIMARY KEY,
    student_id   BIGINT,
    psscsj       DATETIME,
    zmscsj       DATETIME,
    psszsj       DATETIME,
    zmszsj       DATETIME,
    gdsjscsj     VARCHAR(50),
    esfzrs       VARCHAR(50),
    dzrs         VARCHAR(50),
    ztrcsrs      VARCHAR(50),
    rsyb         VARCHAR(50),
    tdwrs        VARCHAR(50),
    xypbrs       VARCHAR(50),
    hzbrs        VARCHAR(50),
    hkjrs        VARCHAR(50),
    hzhzz        VARCHAR(200),
    hzhpha       VARCHAR(50),
    hzhpyr       VARCHAR(50),
    hzmtsm       VARCHAR(200),
    sdts         VARCHAR(50),
    sdtd         VARCHAR(50),
    smsl         VARCHAR(50),
    mtsmlyy      VARCHAR(500),
    wsnc         VARCHAR(50),
    smsmh        VARCHAR(200),
    smbaw        VARCHAR(50),
    hmy          VARCHAR(50),
    hdtrcs       VARCHAR(50),
    fytt         VARCHAR(50),
    ttbw         VARCHAR(50),
    mybzcxrs     VARCHAR(50),
    myxx         VARCHAR(50),
    dhl          VARCHAR(50),
    hxzt         VARCHAR(50),
    bxz          VARCHAR(50),
    jzbzjywt     VARCHAR(500),
    bysmwt       VARCHAR(500),
    yjxljj       VARCHAR(500),
    emjx         VARCHAR(500),
    psxlsj       DATETIME,
    zmxlsj       DATETIME,
    xlyc         VARCHAR(50),
    xlycys       VARCHAR(200),
    pszcxlsj     DATETIME,
    zmzcxlsj     DATETIME,
    psqcsj       DATETIME,
    zmqcsj       DATETIME,
    zjxl         VARCHAR(50),
    nzjx         VARCHAR(50),
    xlqxbj       VARCHAR(200),
    yjrjx        VARCHAR(50),
    qckn         VARCHAR(50),
    csjcnqx      VARCHAR(50),
    xlhz         VARCHAR(200),
    wkhh         VARCHAR(50),
    rjhxs        VARCHAR(50),
    xfhdzsz      VARCHAR(50),
    kqlhpj       VARCHAR(200),
    dzws         VARCHAR(50),
    kds          VARCHAR(50),
    zc           VARCHAR(50),
    cf           VARCHAR(50),
    c_time       DATETIME DEFAULT CURRENT_TIMESTAMP,
    modify_time  DATETIME,
    del_flg      VARCHAR(2) DEFAULT '1',
    count        VARCHAR(20)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 身体活动量表
CREATE TABLE IF NOT EXISTS school_sthd (
    id           BIGINT AUTO_INCREMENT PRIMARY KEY,
    student_id   BIGINT,
    cjzqdpl      VARCHAR(50),
    dssjzqd      VARCHAR(50),
    cjdqdpl      VARCHAR(50),
    dssjdqd      VARCHAR(50),
    jzpl         VARCHAR(50),
    jzsj         VARCHAR(50),
    fkpmjspv     VARCHAR(50),
    fkpmjzsj     VARCHAR(50),
    pmjzpl       VARCHAR(50),
    pmjzsj       VARCHAR(50),
    c_time       DATETIME DEFAULT CURRENT_TIMESTAMP,
    modify_time  DATETIME,
    del_flg      VARCHAR(2) DEFAULT '1',
    count        VARCHAR(20)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
