# Generated by Django 3.0.3 on 2021-05-27 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rele_per', models.CharField(max_length=11)),
                ('rele_per_name', models.CharField(default='', max_length=11)),
                ('title', models.CharField(max_length=128)),
                ('content', models.CharField(max_length=1024)),
                ('rele_target', models.CharField(choices=[('10060001', '普通用户'), ('10060002', '初审人'), ('10060003', '复审人')], default='0', max_length=128)),
                ('close_num', models.IntegerField(default=1)),
                ('rele_time', models.DateTimeField(auto_now_add=True)),
                ('del_flg', models.CharField(choices=[('0', '已删除'), ('1', '有效数据')], default='1', max_length=12)),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'ordering': ['-rele_time'],
            },
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_per', models.CharField(max_length=11)),
                ('sub_unit', models.CharField(default='', max_length=64)),
                ('sub_per_name', models.CharField(default='', max_length=11)),
                ('telephone', models.CharField(max_length=32)),
                ('com_status', models.CharField(choices=[('10070001', '未处理'), ('10070002', '已处理')], default='10070001', max_length=8)),
                ('com_count', models.CharField(max_length=1024)),
                ('feedback', models.CharField(max_length=1024, null=True)),
                ('sub_time', models.DateTimeField(auto_now_add=True)),
                ('del_flg', models.CharField(choices=[('0', '已删除'), ('1', '有效数据')], default='1', max_length=12)),
                ('img_path', models.TextField(default='', null=True)),
            ],
            options={
                'verbose_name': '意见反馈',
                'verbose_name_plural': '意见反馈',
                'ordering': ['-sub_time'],
            },
        ),
        migrations.CreateModel(
            name='PerNoticeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_id', models.CharField(max_length=11)),
                ('close_num', models.IntegerField(default=1)),
                ('del_flg', models.CharField(choices=[('0', '已删除'), ('1', '有效数据')], default='1', max_length=12)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notiopi.Notice')),
            ],
            options={
                'verbose_name': '人员公告日志',
                'verbose_name_plural': '人员公告日志',
                'ordering': ['-notice'],
            },
        ),
    ]
