# Generated by Django 3.0.3 on 2021-05-27 17:10

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=128)),
                ('sex', models.CharField(default='男', max_length=32)),
                ('unit', models.CharField(default='1', max_length=128)),
                ('level', models.IntegerField(choices=[(0, '普通用户'), (1, '管理员')], default=0)),
                ('professional', models.CharField(choices=[('10040001', '助理医师'), ('10040002', '医师'), ('10040003', '主治医师'), ('10040004', '副主任医师'), ('10040005', '主任医师')], default='10040001', max_length=32)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('department', models.CharField(default='', max_length=64)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_per_id', models.CharField(max_length=11)),
                ('login_per_name', models.CharField(max_length=32)),
                ('mana_level', models.CharField(choices=[('10030001', '普通用户'), ('10030002', '管理员用户'), ('10030003', '超级管理员用户')], default='10030001', max_length=32)),
                ('com_ip', models.CharField(max_length=64)),
                ('login_time', models.DateTimeField()),
                ('logout_time', models.DateTimeField()),
                ('del_flg', models.CharField(choices=[('0', '已删除'), ('1', '有效数据')], default='1', max_length=12)),
            ],
            options={
                'verbose_name': '登录日志',
                'verbose_name_plural': '登录日志',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='权限')),
                ('url', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=64)),
                ('del_flg', models.CharField(choices=[('0', '已删除'), ('1', '有效数据')], default='1', max_length=12)),
            ],
            options={
                'verbose_name': '单位',
                'verbose_name_plural': '单位',
                'ordering': ['-unit_name'],
            },
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(default='默认角色名称', max_length=128, unique=True)),
                ('role', models.CharField(max_length=128)),
                ('permissions', models.ManyToManyField(to='login.Permission')),
                ('u_r', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'ordering': ['-role'],
            },
        ),
    ]
