# Generated by Django 3.0.3 on 2023-12-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=64)),
                ('stand_unit', models.CharField(max_length=64)),
                ('unit', models.CharField(max_length=64)),
                ('del_flg', models.CharField(choices=[('0', '已删除'), ('1', '有效数据')], default='1', max_length=12)),
            ],
            options={
                'verbose_name': '药物名称',
                'verbose_name_plural': '药物名称',
                'ordering': ['-drug_name'],
            },
        ),
        migrations.CreateModel(
            name='StandaUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=64)),
                ('stand_unit', models.CharField(max_length=64)),
                ('unit', models.CharField(max_length=64)),
                ('del_flg', models.CharField(choices=[('0', '已删除'), ('1', '有效数据')], default='1', max_length=12)),
            ],
            options={
                'verbose_name': '药物名称',
                'verbose_name_plural': '药物名称',
                'ordering': ['-drug_name'],
            },
        ),
    ]
