# MySQL 密钥配置
# root 密码: root | 业务用户: eksjk | 业务密码: eksjk123
apiVersion: v1
kind: Secret
metadata:
  name: eksjk-mysql-secret
  namespace: eksjk
  labels:
    app: eksjk-mysql
type: Opaque
data:
  # echo -n 'root' | base64
  mysql-root-password: cm9vdA==
  # echo -n 'eksjk' | base64
  mysql-user: ZWtzams=
  # echo -n 'eksjk123' | base64
  mysql-password: ZWtzamsxMjM=
