apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eksjk-minio-pvc
  namespace: eksjk
  labels:
    app: eksjk-minio
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path