# Generated by Django 3.0.3 on 2021-05-27 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamain', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-user_num'], 'verbose_name': '性发育异常', 'verbose_name_plural': '性发育异常'},
        ),
        migrations.AlterModelOptions(
            name='short',
            options={'ordering': ['-user_num'], 'verbose_name': '家族性矮小', 'verbose_name_plural': '家族性矮小'},
        ),
    ]
