# Generated by Django 3.0.3 on 2021-05-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamain', '0002_auto_20210527_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='medrec_num',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
