# Generated by Django 3.0.3 on 2021-06-01 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamain', '0003_patient_medrec_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sexprecocity',
            old_name='rep_hor',
            new_name='chi_com',
        ),
        migrations.RemoveField(
            model_name='sexprecocity',
            name='inp_num',
        ),
        migrations.AddField(
            model_name='sexprecocity',
            name='fam_his',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sexprecocity',
            name='first_time',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='sexprecocity',
            name='lab_exa',
            field=models.CharField(default='无', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='short',
            name='bio_sam_bank',
            field=models.CharField(default='无', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='short',
            name='dia_trea_plan',
            field=models.CharField(default='无', max_length=512, null=True),
        ),
    ]
