# Generated by Django 3.0.3 on 2021-06-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamain', '0004_auto_20210601_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sexprecocity',
            name='lab_exa',
            field=models.CharField(default='无', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='sexprecocity',
            name='phy_exa',
            field=models.CharField(default='无', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='short',
            name='lab_exa',
            field=models.CharField(default='无', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='short',
            name='phy_exa',
            field=models.CharField(default='无', max_length=512, null=True),
        ),
    ]
