# Generated by Django 3.0.3 on 2021-06-01 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamain', '0005_auto_20210601_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sexprecocity',
            old_name='image_path',
            new_name='B_ult_image',
        ),
        migrations.RenameField(
            model_name='short',
            old_name='image',
            new_name='B_ult_image',
        ),
    ]
