# Generated by Django 3.0.3 on 2021-06-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamain', '0006_auto_20210601_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='patfoll',
            name='E2',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='patfoll',
            name='FSH',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='patfoll',
            name='LH',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='patfoll',
            name='T',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='patfoll',
            name='tes_size',
            field=models.CharField(default='无', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='sexprecocity',
            name='bio_sam_bank',
            field=models.CharField(default='无', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='sexprecocity',
            name='dia_trea_plan',
            field=models.CharField(default='无', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='sexprecocity',
            name='electr',
            field=models.CharField(default='无', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='sexprecocity',
            name='gon_B_ult',
            field=models.CharField(default='无', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='sexprecocity',
            name='menarche',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='short',
            name='gon_B_ult',
            field=models.CharField(default='无', max_length=512, null=True),
        ),
    ]
