# Generated by Django 3.0.3 on 2021-06-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamain', '0007_auto_20210603_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patfoll',
            name='dia_trea_plan',
            field=models.CharField(default='无', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='patfoll',
            name='gon_B_ult',
            field=models.CharField(default='无', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='patfoll',
            name='tes_size',
            field=models.CharField(default='无', max_length=512, null=True),
        ),
    ]
