# Generated by Django 3.0.3 on 2021-06-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamain', '0008_auto_20210603_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patfoll',
            name='liv_kid_lip',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
