# Generated by Django 3.0.3 on 2021-06-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamain', '0009_auto_20210603_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='patfoll',
            name='del_flg',
            field=models.CharField(choices=[('0', '已删除'), ('1', '有效数据')], default='1', max_length=4),
        ),
    ]
