# Generated by Django 3.0.3 on 2021-06-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamain', '0010_patfoll_del_flg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sexprecocity',
            options={'ordering': ['-user_num'], 'verbose_name': '中枢性性早熟', 'verbose_name_plural': '中枢性性早熟'},
        ),
        migrations.AddField(
            model_name='sexprecocity',
            name='SRY',
            field=models.CharField(choices=[('1', '阳性'), ('2', '阴性')], default='1', max_length=4),
        ),
        migrations.AddField(
            model_name='sexprecocity',
            name='ami_aci_mut',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sexprecocity',
            name='base_mut',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='sexprecocity',
            name='gen_mut_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='sexprecocity',
            name='mut_kind',
            field=models.CharField(choices=[('10010001', '错义突变'), ('10010002', '无义突变'), ('10010003', '截断突变'), ('10010004', '移码突变'), ('10010005', '剪接位点突变'), ('10010006', '同义突变'), ('10010007', '非编码区突变'), ('10010008', '剪接位点附近的突变')], default='1', max_length=8),
        ),
        migrations.AddField(
            model_name='sexprecocity',
            name='sour_mut',
            field=models.CharField(choices=[('0', '新生'), ('1', '父'), ('2', '母')], default='1', max_length=4),
        ),
        migrations.AddField(
            model_name='sexprecocity',
            name='spe_kar',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='short',
            name='SRY',
            field=models.CharField(choices=[('1', '阳性'), ('2', '阴性')], default='1', max_length=4),
        ),
        migrations.AddField(
            model_name='short',
            name='ami_aci_mut',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='short',
            name='base_mut',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='short',
            name='gen_mut_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='short',
            name='mut_kind',
            field=models.CharField(choices=[('10010001', '错义突变'), ('10010002', '无义突变'), ('10010003', '截断突变'), ('10010004', '移码突变'), ('10010005', '剪接位点突变'), ('10010006', '同义突变'), ('10010007', '非编码区突变'), ('10010008', '剪接位点附近的突变')], default='1', max_length=8),
        ),
        migrations.AddField(
            model_name='short',
            name='sour_mut',
            field=models.CharField(choices=[('0', '新生'), ('1', '父'), ('2', '母')], default='1', max_length=4),
        ),
        migrations.AddField(
            model_name='short',
            name='spe_kar',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
