# Generated by Django 3.0.3 on 2021-06-22 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datamain', '0011_auto_20210615_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='patfoll',
            name='up_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
