# Generated by Django 3.0.3 on 2021-06-22 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamain', '0012_patfoll_up_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patfoll',
            name='up_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
