# Generated by Django 3.0.3 on 2021-07-26 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamain', '0013_auto_20210622_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='past_his',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='patfoll',
            name='foll_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='patient',
            name='fet_pro_his',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
