# Generated by Django 3.0.3 on 2021-07-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamain', '0014_auto_20210726_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='patfoll',
            name='DHT',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='patfoll',
            name='SHBG',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='patfoll',
            name='yltg',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
