# Generated by Django 3.0.3 on 2021-11-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamain', '0015_auto_20210726_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='body_other',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='breast_dev',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='ex_genitalia',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='pubic_hair',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gonadal_sex',
            field=models.CharField(default='1', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(default='1', max_length=4, null=True),
        ),
    ]
