"""
Django settings for wjwsjk project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'p@m&_v$ijv7hsd0w_4h4i#j9ra6j75-b*l)f$_27j+$#ix1i8y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'login',
    'datamain',
    'captcha',
    'notiopi',
    'xcx',
    'school',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'login.middleware.middleware.UseuMiddleware',
]

ROOT_URLCONF = 'wjwsjk.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wjwsjk.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

# 使用mysql，本地使用
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'eksjk',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': 'localhost',
        'PORT': '3306',
        'CONN_MAX_AGE': 9
    }
}
# # 使用mysql，线上使用
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'eksjk',
#         'USER': 'ra_dev_server',
#         'PASSWORD': 'Ramed025',
#         'HOST': '122.224.146.11',
#         'PORT': '3306',
#         'CONN_MAX_AGE': 9
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'



USE_I18N = True

USE_L10N = True

USE_TZ = False
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/


STATIC_URL = '/static/'
### 项目相关配置 ###
COLLECTOR_HOST = 'tcp://127.0.0.1:18736'

# 密钥所在路径，需改为绝对路径，实际部署时请用以下命令重新生成
# openssl genrsa -out rsa_1024_priv.pem 1024
# openssl rsa -pubout -in rsa_1024_priv.pem -out rsa_1024_pub.pem
PRIVATE_KEY_PATH = 'D:/project/eksjk/eksjk/wjwsjk/keys/rsa_1024_priv.pem'
PUBLIC_KEY_PATH = 'D:/project/eksjk/eksjk/wjwsjk/keys/rsa_1024_pub.pem'
# PRIVATE_KEY_PATH = '/opt/eksjk/eksjk/wjwsjk/keys/rsa_1024_priv.pem'
# PUBLIC_KEY_PATH = '/opt/eksjk/eksjk/wjwsjk/keys/rsa_1024_pub.pem'

# 引用Django自带的User表，继承使用时需要设置
AUTH_USER_MODEL = "login.User"

# session 设置
SESSION_COOKIE_AGE = 60 * 120  # 120分钟
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True

# 图片储存路径
IMG_PATH = "E:/imgtest/"
# IMG_PATH = "/RAID5/eksjk/storage/"
# mask文件储存路径
MASK_PATH = "E:/imgtest/"
# MASK_PATH = "/RAID5/eksjk/storage/"


# 压缩包储存路径
ZIP_PATH = "E:/imgtest/"
# ZIP_PATH = "/RAID5/eksjk/storage/"

# 统计报表导出路径
STA_PATH = "E:/imgtest"
# STA_PATH = "/RAID5/eksjk/storage/"

# 验证码组件设置
CAPTCHA_FONT_PATH = '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf'
CAPTCHA_LETTER_ROTATION = (-50, 50)

# 解决报错
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'





"""
    关于图片上传
"""
# 媒体文件根目录
MEDIA_ROOT = 'E:/img'
MEDIA_URL = '/media/'

# 自定义存储图片的目录
BABY_IMAGES_DIR = os.path.join(MEDIA_ROOT, 'baby_images')
os.makedirs(BABY_IMAGES_DIR, exist_ok=True)  # 确保目录存在
