# Generated by Django 5.2.4 on 2025-09-19 15:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cbq',
            options={'ordering': ['-id'], 'verbose_name': '儿童气质问卷CBQ', 'verbose_name_plural': '儿童气质问卷CBQ'},
        ),
        migrations.RenameField(
            model_name='cbq',
            old_name='bgxxs',
            new_name='bhphy',
        ),
        migrations.RenameField(
            model_name='cbq',
            old_name='bhzjjkn',
            new_name='bnzdhsc',
        ),
        migrations.RenameField(
            model_name='cbq',
            old_name='bljhzhfuzsm',
            new_name='bwcjs',
        ),
        migrations.RenameField(
            model_name='cbq',
            old_name='bnfwzwn',
            new_name='bxhcyyx',
        ),
        migrations.RenameField(
            model_name='cbq',
            old_name='bqsjbyhz',
            new_name='bzzsl',
        ),
        migrations.RenameField(
            model_name='cbq',
            old_name='bxbgjz',
            new_name='dfmwbpj',
        ),
        migrations.RenameField(
            model_name='cbq',
            old_name='bxhzzcn',
            new_name='dqqgk',
        ),
        migrations.RenameField(
            model_name='cbq',
            old_name='bzyhzzsm',
            new_name='drhrbjs',
        ),
        migrations.RenameField(
            model_name='cbq',
            old_name='dhzbjsf',
            new_name='gmssby',
        ),
        migrations.RenameField(
            model_name='cbq',
            old_name='dhzknysdc',
            new_name='gxhaj',
        ),
        migrations.RenameField(
            model_name='cbq',
            old_name='dhzmyjc',
            new_name='hcsjsyxhj',
        ),
        migrations.RenameField(
            model_name='cbq',
            old_name='dhzrzhd',
            new_name='hhx',
        ),
        migrations.RenameField(
            model_name='cbq',
            old_name='dhzshysgx',
            new_name='hmzs',
        ),
        migrations.RenameField(
            model_name='cbq',
            old_name='gjhzxqpytc',
            new_name='hpyz',
        ),
        migrations.RenameField(
            model_name='cbq',
            old_name='glhzzs',
            new_name='htzz',
        ),
        migrations.RenameField(
            model_name='cbq',
            old_name='hsyqyty',
            new_name='jtjhmdx',
        ),
        migrations.RenameField(
            model_name='cbq',
            old_name='hzbfcdm',
            new_name='mrjrxdf',
        ),
        migrations.RenameField(
            model_name='cbq',
            old_name='hzbgxbpp',
            new_name='nwczb',
        ),
        migrations.RenameField(
            model_name='cbq',
            old_name='hzfcbzh',
            new_name='nzyfmxyf',
        ),
        migrations.RenameField(
            model_name='cbq',
            old_name='hzgxbxyq',
            new_name='pyzhfz',
        ),
        migrations.RenameField(
            model_name='cbq',
            old_name='hzsffcwsw',
            new_name='qwcsbxf',
        ),
        migrations.RenameField(
            model_name='cbq',
            old_name='hzxzmyjzy',
            new_name='ryaf',
        ),
        migrations.RenameField(
            model_name='cbq',
            old_name='hzyddycgfzj',
            new_name='sqgcsj',
        ),
        migrations.RenameField(
            model_name='cbq',
            old_name='hzysmgsm',
            new_name='syayqxd',
        ),
        migrations.RenameField(
            model_name='cbq',
            old_name='hzzcyspp',
            new_name='trjccsj',
        ),
        migrations.RenameField(
            model_name='cbq',
            old_name='khzzs',
            new_name='wsjlcp',
        ),
        migrations.RenameField(
            model_name='cbq',
            old_name='pyhzjzjd',
            new_name='xcsba',
        ),
        migrations.RenameField(
            model_name='cbq',
            old_name='rhzmbwsm',
            new_name='xhdtrcg',
        ),
        migrations.RenameField(
            model_name='cbq',
            old_name='slshzsc',
            new_name='xhgq',
        ),
        migrations.RenameField(
            model_name='cbq',
            old_name='thzyqyx',
            new_name='xhmxhd',
        ),
        migrations.RenameField(
            model_name='cbq',
            old_name='thzzs',
            new_name='xhrhhd',
        ),
        migrations.RenameField(
            model_name='cbq',
            old_name='tyjsysyx',
            new_name='xrshx',
        ),
        migrations.RenameField(
            model_name='cbq',
            old_name='wlyqysmz',
            new_name='zscm',
        ),
        migrations.RenameField(
            model_name='cbq',
            old_name='wmyyzpp',
            new_name='zyktxsw',
        ),
        migrations.RenameField(
            model_name='cbq',
            old_name='yqhzjyy',
            new_name='zywx',
        ),
        migrations.RenameField(
            model_name='cbq',
            old_name='ysdfsbyhz',
            new_name='zztscsj',
        ),
        migrations.RemoveField(
            model_name='cbq',
            name='ysqz',
        ),
        migrations.RemoveField(
            model_name='cbq',
            name='yxchtw',
        ),
        migrations.RemoveField(
            model_name='cbq',
            name='zjmblchz',
        ),
        migrations.RemoveField(
            model_name='cbq',
            name='zjmjtyq',
        ),
        migrations.CreateModel(
            name='Mqzyfs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hzbgxbpp', models.CharField(max_length=32, null=True)),
                ('hzysmgsm', models.CharField(max_length=32, null=True)),
                ('hzsffcwsw', models.CharField(max_length=32, null=True)),
                ('hzgxbxyq', models.CharField(max_length=32, null=True)),
                ('hzbfcdm', models.CharField(max_length=32, null=True)),
                ('hzfcbzh', models.CharField(max_length=32, null=True)),
                ('hzyddycgfzj', models.CharField(max_length=32, null=True)),
                ('glhzzs', models.CharField(max_length=32, null=True)),
                ('thzzs', models.CharField(max_length=32, null=True)),
                ('gjhzxqpytc', models.CharField(max_length=32, null=True)),
                ('dhzknysdc', models.CharField(max_length=32, null=True)),
                ('yxchtw', models.CharField(max_length=32, null=True)),
                ('bxbgjz', models.CharField(max_length=32, null=True)),
                ('wmyyzpp', models.CharField(max_length=32, null=True)),
                ('bnfwzwn', models.CharField(max_length=32, null=True)),
                ('bxhzzcn', models.CharField(max_length=32, null=True)),
                ('rhzmbwsm', models.CharField(max_length=32, null=True)),
                ('dhzshysgx', models.CharField(max_length=32, null=True)),
                ('bzyhzzsm', models.CharField(max_length=32, null=True)),
                ('zjmblchz', models.CharField(max_length=32, null=True)),
                ('hzxzmyjzy', models.CharField(max_length=32, null=True)),
                ('bqsjbyhz', models.CharField(max_length=32, null=True)),
                ('bljhzhfuzsm', models.CharField(max_length=32, null=True)),
                ('ysdfsbyhz', models.CharField(max_length=32, null=True)),
                ('wlyqysmz', models.CharField(max_length=32, null=True)),
                ('dhzmyjc', models.CharField(max_length=32, null=True)),
                ('bhzjjkn', models.CharField(max_length=32, null=True)),
                ('khzzs', models.CharField(max_length=32, null=True)),
                ('dhzrzhd', models.CharField(max_length=32, null=True)),
                ('tyjsysyx', models.CharField(max_length=32, null=True)),
                ('dhzbjsf', models.CharField(max_length=32, null=True)),
                ('hsyqyty', models.CharField(max_length=32, null=True)),
                ('thzyqyx', models.CharField(max_length=32, null=True)),
                ('yqhzjyy', models.CharField(max_length=32, null=True)),
                ('hzzcyspp', models.CharField(max_length=32, null=True)),
                ('bgxxs', models.CharField(max_length=32, null=True)),
                ('slshzsc', models.CharField(max_length=32, null=True)),
                ('ysqz', models.CharField(max_length=32, null=True)),
                ('zjmjtyq', models.CharField(max_length=32, null=True)),
                ('pyhzjzjd', models.CharField(max_length=32, null=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('del_flg', models.CharField(choices=[('0', '已删除'), ('1', '有效数据')], default='1', max_length=4)),
                ('student', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='school.student')),
            ],
            options={
                'verbose_name': '母亲照养方式问卷',
                'verbose_name_plural': '母亲照养方式问卷',
                'ordering': ['-id'],
            },
        ),
    ]
