# Generated by Django 5.2.4 on 2025-09-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_cbq_options_rename_bgxxs_cbq_bhphy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smxg',
            name='mybzcxrs',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='smxg',
            name='pszcxlsj',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smxg',
            name='zmzcxlsj',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smxg',
            name='psxlsj',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='smxg',
            name='zmxlsj',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
