# Generated by Django 5.2.4 on 2025-10-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_smxg_mybzcxrs_smxg_pszcxlsj_smxg_zmzcxlsj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
