# Generated by Django 5.2.4 on 2025-10-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbq',
            name='count',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='cchkn',
            name='count',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='mqzyfs',
            name='count',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='pmbl',
            name='count',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='qzhd',
            name='count',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='smxg',
            name='count',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='sthd',
            name='count',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='count',
            field=models.TextField(default='', null=True),
        ),
    ]
